- name: Check sudo Password
  command: whoami
  become: yes
  become_method: sudo

# https://github.com/caskroom/homebrew-cask
- name: Install Homebrew-Cask
  homebrew:
    name: caskroom/cask/brew-cask
    state: present

# https://github.com/caskroom/homebrew-fonts
- name: Tap Caskroom Fonts
  homebrew_tap:
    tap: caskroom/fonts

# - name: Update Homebrew
#   homebrew:
#     update_homebrew: yes

- name: Install system packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - autojump
    - coreutils
    - enchant
    - fasd
    - git
    - homebrew/dupes/rsync
    - jq
    - mercurial
    - openssl
    - p7zip
    - readline
    - s3cmd
    - ssh-copy-id
    - tree
    - zsh-completions

# https://github.com/sindresorhus/quick-look-plugins
- name: Install system plugins
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - quicklook-csv
    - qlimagesize

- name: Checkout dircolors-solarized
  git:
    repo: https://github.com/seebi/dircolors-solarized.git
    dest: "{{ ansible_env.HOME }}/.dircolors-solarized"

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile
  when: ansible_env.SHELL == "/bin/zsh"

- name: Create Projects directory
  file:
    path: "{{ ansible_env.HOME }}/Projects"
    state: directory
