- name: Check sudo password
  command: whoami
  become: yes
  become_method: sudo

# https://github.com/robbyrussell/oh-my-zsh
- name: stat .oh-my-zsh directory
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/"
  register: oh_my_zsh_dir

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: not oh_my_zsh_dir.stat.exists

# https://github.com/caskroom/homebrew-versions
- name: Tap Caskroom versions
  homebrew_tap:
    tap: caskroom/versions

# https://github.com/caskroom/homebrew-fonts
- name: Tap Caskroom fonts
  homebrew_tap:
    tap: caskroom/fonts

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install system packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - autojump
    - coreutils
    - enchant
    - fasd
    - git
    - grc
    - homebrew/dupes/rsync
    - jq
    - mackup
    - mercurial
    - openssl
    - p7zip
    - readline
    - s3cmd
    - ssh-copy-id
    - tree
    - wget
    - zsh-completions

# https://github.com/sindresorhus/quick-look-plugins
- name: Install system plugins
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - qlimagesize
    - quicklook-csv
    - quicklook-json

# https://github.com/tarruda/zsh-autosuggestions
- name: Checkout zsh-autosuggestions
  git:
    repo: git://github.com/tarruda/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: yes

# https://github.com/seebi/dircolors-solarized
- name: Checkout dircolors-solarized
  git:
    repo: git@github.com:seebi/dircolors-solarized.git
    dest: "{{ ansible_env.HOME }}/.dircolors-solarized"
    update: yes

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile"
  when: ansible_env.SHELL == "/bin/zsh"

- name: Run hal sync
  command: "{{ REPO_ROOT }}/bin/hal sync"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Downloads"
    - "{{ ansible_env.HOME }}/Projects"
