- name: Check sudo Password
  command: whoami
  become: yes
  become_method: sudo

# https://github.com/caskroom/homebrew-cask
- name: Install Homebrew-Cask
  homebrew:
    name: caskroom/cask/brew-cask
    state: present

# https://github.com/caskroom/homebrew-fonts
- name: Tap Caskroom-Fonts
  homebrew_tap:
    tap: caskroom/fonts

# - name: Update Homebrew
#   homebrew:
#     update_homebrew: yes

- name: Checkout dircolors-solarized
  git:
    repo: https://github.com/seebi/dircolors-solarized.git
    dest: ~/.dircolors-solarized

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile
  when: ansible_env.SHELL == "/bin/zsh"
