# https://www.virtualbox.org/
- name: Install Virtualbox
  homebrew_cask:
    name: virtualbox
    state: present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ BREW_CASK_APPDIR }}"

- name: Install VirtVirtualBox Extension Pack
  homebrew_cask:
    name: virtualbox-extension-pack
    state: present

# https://www.docker.com/
- name: Install Docker and extras
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-machine
    - docker-compose

- name: Create resolver directory
  file:
    path: /etc/resolver
    state: directory
    mode: 0755
  become: yes
  become_method: sudo

# CAUTION: `src` must be absolute path when `state` is `link`
- name: Link .dev resolver file
  file:
    src: "{{ REPO_ROOT }}/playbooks/roles/docker/files/resolver_dev.conf"
    dest: /etc/resolver/dev
    state: link
    force: yes
  become: yes
  become_method: sudo

# assign the result of this task to a variable named `exports`
# the variable can be used in another task
- name: Add NFS share to /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "{{ item }}"
    create: yes
  with_items:
    - /Users 192.168.99.100 -alldirs -mapall=0:80
  become: yes
  become_method: sudo
  register: nfs_exports

- name: Restart nfsd
  command: nfsd restart
  become: yes
  become_method: sudo
  when: nfs_exports.changed

- name: Enable Docker Machine environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/docker/files/docker_machine_profile
  when: ansible_env.SHELL == "/bin/zsh"

- name: Create the Docker Machine VM
  command: "{{ REPO_ROOT }}/bin/hal create"
