# https://github.com/yyuu/pyenv
- name: Install pyenv and extras
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - readline
    - openssl
    - pyenv
    # - pyenv-virtualenv
    # - pyenv-virtualenvwrapper

- name: Install Python 2 via pyenv
  command: "pyenv install {{ PYTHON_2_VERSION }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_2_VERSION }}"

- name: Install Python 3 via pyenv
  command: "pyenv install {{ PYTHON_3_VERSION }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_3_VERSION }}"

- name: Install Python 2 tools
  pip:
    executable: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_2_VERSION }}/bin/pip"
    requirements: "{{ REPO_ROOT }}/playbooks/roles/python/files/requirements.txt"

- name: Install Python 3 tools
  pip:
    executable: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_3_VERSION }}/bin/pip3"
    requirements: "{{ REPO_ROOT }}/playbooks/roles/python/files/requirements.txt"

- name: Enable pyenv environment in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/python/files/pyenv_profile
  when: ansible_env.SHELL == "/bin/bash"

- name: Enable pyenv environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/python/files/pyenv_profile
  when: ansible_env.SHELL == "/bin/zsh"
