# https://github.com/moovweb/gvm
- name: Install gvm
  command: "bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.gvm/"

- name: Install Go 1.4
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    gvm install go1.4 && \
    gvm use go1.4 --default
  args:
    creates: "{{ ansible_env.HOME }}/.gvm/gos/go1.4"

- name: Install Go newer version
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    gvm install go{{ GO_VERSION }} && \
    gvm use go{{ GO_VERSION }} --default
  args:
    creates: "{{ ansible_env.HOME }}/.gvm/gos/go{{ GO_VERSION }}"

- name: Create oh-my-go directory
  file:
    path: "{{ ansible_env.HOME }}/Projects/oh-my-go"
    state: directory

- name: Install must-have packages for Go
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    {{ ansible_env.HOME }}/.gvm/gos/go{{ GO_VERSION }}/bin/go get {{ item }}
  with_items:
    - github.com/golang/lint/golint
    - github.com/nsf/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/godoc

- name: Enable gvm environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile
  when: ansible_env.SHELL == "/bin/zsh"
