# https://github.com/moovweb/gvm
- name: stat .gvm directory
  stat:
    path: "{{ ansible_env.HOME }}/.gvm/"
  register: gvm_dir

- name: Install gvm
  shell: "bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)"
  args:
    executable: /bin/bash
  when: not gvm_dir.stat.exists

- name: stat Go 1.4 version directory
  stat:
    path: "{{ ansible_env.HOME }}/.gvm/gos/go1.4"
  register: go14_version_dir

- name: Install Go 1.4
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    gvm install go1.4
  when: not go14_version_dir.stat.exists

- name: stat Go newer version directory
  stat:
    path: "{{ ansible_env.HOME }}/.gvm/gos/go{{ GO_VERSION }}"
  register: go_newer_version_dir

- name: Install Go newer version
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    gvm use go1.4 && \
    gvm install go{{ GO_VERSION }} && \
    gvm use go{{ GO_VERSION }} --default
  when: not go_newer_version_dir.stat.exists

- name: Create oh-my-go directory
  file:
    path: "{{ ansible_env.HOME }}/Projects/oh-my-go"
    state: directory

- name: Install must-have packages for Go
  shell: >
    source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile && \
    go get -u {{ item }}
  with_items:
    - github.com/golang/lint/golint
    - github.com/mattn/goveralls
    - github.com/nsf/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/vet

- name: Enable gvm environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/go/files/gvm_profile
  when: ansible_env.SHELL == "/bin/zsh"
