version: "2"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  dns:
    image: andyshinn/dnsmasq:2.75
    ports:
      - "192.168.99.100:53:53/tcp"
      - "192.168.99.100:53:53/udp"
    cap_add:
      - NET_ADMIN
    command: --address=/dev/192.168.99.100
    restart: always

networks:
  default:
    driver: bridge
