version: "2"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: "bridge"
    restart: always
  dns:
    image: andyshinn/dnsmasq:2.76
    ports:
      - "53535:53/tcp"
      - "53535:53/udp"
    cap_add:
      - NET_ADMIN
    command: --address=/dev/127.0.0.1
    network_mode: "bridge"
    restart: always
