version: "2"

services:
  proxy:
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  dns:
    image: andyshinn/dnsmasq:2.76
    ports:
      - "53535:53/tcp"
      - "53535:53/udp"
    cap_add:
      - NET_ADMIN
    command: --address=/dev/127.0.0.1
    restart: always
