# https://github.com/tj/n
- name: Install n
  command: "curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y"
  args:
    creates: "{{ ansible_env.HOME }}/.n/"
    executable: /bin/bash

- name: Enable nvm environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/n_profile
  when: ansible_env.SHELL == "/bin/zsh"
