- name: Install Node.js
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - node@8

- name: Install Node.js tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - yarn
