# https://github.com/creationix/nvm
- name: Install nvm
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - nvm

- name: stat Node.js version directory
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ NODE_VERSION }}"
  register: node_version_dir

- name: Install Node.js
  shell: >
    . /usr/local/opt/nvm/nvm.sh && \
    nvm install {{ NODE_VERSION }} && \
    nvm use {{ NODE_VERSION }} && \
    nvm alias default {{ NODE_VERSION }}
  when: not node_version_dir.stat.exists

- name: Enable nvm environment in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/nvm_profile
  when: ansible_env.SHELL == "/bin/bash"

- name: Enable nvm environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/nvm_profile
  when: ansible_env.SHELL == "/bin/zsh"
