# https://github.com/creationix/nvm
- name: Install nvm
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - nvm

- name: Enable nvm environment in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/nvm_profile
  when: ansible_env.SHELL == "/bin/bash"

- name: Enable nvm environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/nvm_profile
  when: ansible_env.SHELL == "/bin/zsh"
